version: '3.8'

services:
  cryptorun:
    image: cryptorun:1.0
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - CURRENCY_API_KEY=d62a574e27594811fe201e5e
    depends_on:
      - redis
    networks:
      - backend

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - backend

  h2-database:
    image: "buildo/h2database:latest"
    ports:
      - "8082:8082"
    environment:
      - DATABASE_NAME=testdb
    networks:
      - backend

networks:
  backend:
